services:
  - type: web
    name: runmaster-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: STRAVA_REDIRECT_URI
        sync: false
      - key: FRONTEND_URL
        sync: false 